// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyTbC8dYJLILzU3yypHQAKeLT68Mp6EFA',
    appId: '1:979477090572:web:977cff4f54a5e2e030b929',
    messagingSenderId: '979477090572',
    projectId: 'nexo-81bcf',
    authDomain: 'nexo-81bcf.firebaseapp.com',
    storageBucket: 'nexo-81bcf.firebasestorage.app',
    measurementId: 'G-R6EDSXY15C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJo2-LcAJNVrKUHIQQAdpEFAd5hcEvVuY',
    appId: '1:979477090572:android:3a395ad3fb61529b30b929',
    messagingSenderId: '979477090572',
    projectId: 'nexo-81bcf',
    storageBucket: 'nexo-81bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDggKduXOs3qNVdsv83cPyvMjmzzwN1cwM',
    appId: '1:979477090572:ios:058ed4934212ab6230b929',
    messagingSenderId: '979477090572',
    projectId: 'nexo-81bcf',
    storageBucket: 'nexo-81bcf.firebasestorage.app',
    iosBundleId: 'com.example.nexo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDggKduXOs3qNVdsv83cPyvMjmzzwN1cwM',
    appId: '1:979477090572:ios:058ed4934212ab6230b929',
    messagingSenderId: '979477090572',
    projectId: 'nexo-81bcf',
    storageBucket: 'nexo-81bcf.firebasestorage.app',
    iosBundleId: 'com.example.nexo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyTbC8dYJLILzU3yypHQAKeLT68Mp6EFA',
    appId: '1:979477090572:web:3ef2cafc90c783c430b929',
    messagingSenderId: '979477090572',
    projectId: 'nexo-81bcf',
    authDomain: 'nexo-81bcf.firebaseapp.com',
    storageBucket: 'nexo-81bcf.firebasestorage.app',
    measurementId: 'G-B7R7EZL9E2',
  );
}
